# SharedMemoryClassifier参数
CLASSIFIER_SHM_KEY : 0x0250
classifier_model_relative_path : "src/shared_files/models/model_rm2026_openvino/model.xml"

YOLO_POSE_SHM_KEY : 0x0070
yolo_pose_model_relative_path : "src/shared_files/models/armor-oneclass-yolo11n-pose-best_int8_openvino_model"

# ArmorDetect_Node 参数
enemy_color : "BLUE"

use_yolo_pose : false

camera_ExposureTime : 5000.0  # 5000.0
camera_Gain : 16.0            # 16.0
bullet_velocity_ : 15.0
current_pitch_ : 0.0
current_yaw_ : 0.0
# 相机光心相对枪口的偏移（xyz分别为相机系下向右、向前、向上）
delta_x_ : 50.0   # 待修正
delta_y_ : -50.0  # 待测
delta_z_ : 30.0   # 待修正

max_armor_position_height : 1500.0 # 最大装甲板高度，超过此值视为无效

pc_ip : "192.168.10.25"
cam_ip : "192.168.10.10"

video_relative_path : "InputVideo/infantry_blue.mp4" # 使用视频输入时的视频路径
images_relative_path : "InputImages" # 使用图片输入时的图片文件夹路径

frame_rate : 30.0
serial_delay_time : 30.0 # ms

# 根据相机内参自动提取，不再需要手动输入
# yaw_rad_to_x_pixel_ratio : 1300.0
# pitch_rad_to_y_pixel_ratio : 1350.0

reset_predictor_time : 1000.0 # ms

pre_predict_time_not_aim : 500.0
pre_predict_time : 2000.0

# RMM火控设置
after_target_change_ceasefire_ms : 200
before_target_change_ceasefire_ms : 100
aim_center_vyaw_threshold : 3.0
aim_center_yaw_bias_expand : 0.0 # 0.174

armor_distance_smooth_factor : 1.0 # 0.05

# Params.h 参数设置
min_light_height : 8 # 8
light_min_area : 3 # 10
light_max_area : 4096
max_light_wh_ratio : 100.0 # 10.0
min_light_wh_ratio : 1 # 0.1
light_max_tilt_angle : 60.0

# LightBarDetector 参数
binary_img_THRESHOLD : 180 # 128 # 180 # 240
subtract_value : 120
color_rect_expand_FACTOR : 1.5
mean_color_diff_THRESHOLD_BLUE : 20.0
mean_color_diff_THRESHOLD_RED : 10.0
THRES_MAX_COLOR_RED : 60
THRES_MAX_COLOR_BLUE : 100
light_bar_max_angle : 30.0

# ArmorDetector 参数
corners_expand_ratio : 1.5 # 装甲板角点坐标扩大比例
corners_narrow_ratio : 0.8
is_ture_yolo_armor_brightness_ratio : 1.0
height_correct_ratio_small : 1.22 # 角点坐标修正比例系数 # 1.02 # 0.98 # 1.24 # 1.02
width_correct_ratio_small : 1.12 # 1.12
height_correct_ratio_large : 1.26 # 1.04
width_correct_ratio_large : 1.06
max_angle_diff : 22.5        # 最大角度差 # 22.5 # 30
max_height_diff_ratio : 0.65  # 最大高度差比例 # 0.65 # 1.2
max_length_direction_mismatch_ratio : 1.5 # 最大长度方向错位比例 # 2.0
min_light_distance : 5.0     # 最小灯条距离 
max_light_distance : 50.0    # 最大灯条距离
min_armor_confidence : 0.3   # 最小置信度阈值 # 0.3
#camera_matrix: # 相机内参矩阵
#  - [810.40948926, 0.00000000e+00, 611.41991188]
#  - [0.00000000e+00, 813.22312056, 385.16020552]
#  - [0.00000000e+00, 0.00000000e+00, 1.00000000e+00]
#dist_coeffs: [-0.08153923,  0.49331671,  0.0017929,  -0.00437156, -1.28439103] # 畸变系数
camera_matrix: # 相机内参矩阵
  - [1.31280460e+03, 0.00000000e+00, 6.38736364e+02]
  - [0.00000000e+00, 1.31309593e+03, 5.34133502e+02]
  - [0.00000000e+00, 0.00000000e+00, 1.00000000e+00]
dist_coeffs: [-0.05392145, -0.02516686, -0.00222499, -0.00149047,  0.43693918] # 畸变系数
max_expected_small_distance_mismatch_ratio : 0.35
max_expected_large_distance_mismatch_ratio : 0.35

# ArmorClassifier 参数
MAX_ROI_SAVE_COUNT : 20000  # 最大保存数量
classify_classes : 8
IS_ARMOR_THRESHOLD : 0.5
IS_LARGE_THRESHOLD : 0.5
CLASSIFY_THRESHOLD : 0.5
INPUT_HEIGHT : 48
INPUT_WIDTH : 64
MAX_TRACKING_AGE_MS : 100  # 最大跟踪时间100ms // DEBUG // 100 // 300
MIN_TRACKING_COUNT : 2     # 最小连续跟踪次数           // 2
IS_NEAR_MAX_DIST_RATIO : 1.5     # 50.0
armor_tracker_fit_step : 5
armor_tracker_predict_step : 5

