# SharedMemoryClassifier参数
CLASSIFIER_SHM_KEY : 0x0250
classifier_model_relative_path : "src/shared_files/models/model_rm2026_openvino/model.xml"

YOLO_POSE_SHM_KEY : 0x0070
yolo_pose_model_relative_path : "src/shared_files/models/armor-oneclass-yolo11n-pose-best_int8_openvino_model"

# ArmorDetect_Node 参数
init_enemy_color : "BLUE" # 初始敌方颜色，连接至电控后会自动获取敌方颜色并覆盖此值
use_yolo_pose : false     # 传统视觉无法识别装甲板时的备用方案，精度较（？）低
max_armor_position_height : 1500.0 # 最大装甲板高度，超过此值视为无效

camera_ExposureTime : 5000.0  # 5000.0
camera_Gain : 16.0            # 16.0
bullet_velocity_ : 15.0   # 初始弹速，连接至电控后会自动获取实时弹速并覆盖此值
# 相机光心相对枪口的偏移（xyz分别为相机系下向右、向前、向上）
delta_x_ : 50.0   # 待修正
delta_y_ : -50.0  # 待测
delta_z_ : 30.0   # 待修正

pc_ip : "192.168.10.25"
cam_ip : "192.168.10.10"

video_relative_path : "InputVideo/infantry_blue.mp4"    # 使用视频输入时的视频路径
images_relative_path : "InputImages"                    # 使用图片输入时的图片文件夹路径

RMM_visualize_zoom_out_factor : 10.0 # 平面可视化缩放系数，该值越大视野范围越大

frame_rate : 30.0   # fps
serial_delay_time : 30.0 # ms           电控传来的信息相对相机画面快的时间，将对电控信息再延迟这个时间以同步两者
extra_predict_time : 0.150 # s          除了弹丸飞行时间以外的需要预测器补偿的总时间

pre_predict_time_not_aim : 500.0 # ms 在看到目标的这段时间内不启动自瞄，防止因电控云台角度信息延迟而震荡
pre_predict_time : 2000.0 # ms 在看到目标的这段时间内自瞄直接瞄准当前装甲板位置，不使用预测器预测的位置，待有足够观测值后再使用预测值
reset_predictor_time : 1000.0 # ms 超过这段时间未观测到某一类装甲板，将停止这一类装甲板的预测并重置预测器

# 控制PID参数
pitch_integration_max_degree : 60.0
pitch_integration_min_degree : -60.0
yaw_integration_max_degree : 60.0
yaw_integration_min_degree : -60.0
command_picth_kp: 1.0
command_picth_integration_speed: 0.02
command_yaw_kp: 1.0
command_yaw_integration_speed: 0.02

# 火控设置
after_target_change_ceasefire_ms : 200                      # 切换至下一块装甲板后，在这段时间内不开火
before_target_change_ceasefire_ms : 100                     # 切换至下一块装甲板前，在这段时间内提前停火
aim_center_vyaw_upper_threshold : 3.0                       # 敌方小陀螺超过此转速（rad/s）后，切换为瞄准整车中心，预测装甲板到达中心的时间开火
aim_center_vyaw_lower_threshold : 2.5                       # 切换为上述瞄准中心开火模式后，小陀螺转速下降至此值后换回原模式
aim_center_yaw_bias_expand : 0.0                            # 瞄准中心开火模式下，相对于只在装甲板覆盖的角度范围开火，增加此值对应的角度。此值单位为rad
low_vyaw_change_target_delta_yaw_threshold_degree : 10.0    # 角速度较低时，切换目标装甲板需要比当前目标装甲板更靠近的角度，防止在两块装甲板角度相近时目标来回跳变。此值单位为度
low_vyaw_threshold : 0.3                                    # 上述防跳变启用的角速度阈值（rad/s）

choose_armor_yaw_bias_degree : 0.0 # 相对于选择离自身最近的90°(前哨站120°)，提前这个角度切换到下一块装甲板。此值单位为度

# Params.h 参数设置
min_light_height : 8 # 8
light_min_area : 3 # 10
light_max_area : 4096
max_light_wh_ratio : 100.0 # 10.0
min_light_wh_ratio : 1 # 0.1
light_max_tilt_angle : 60.0

# LightBarDetector 参数
binary_img_THRESHOLD : 180 # 128 # 180 # 240
subtract_value : 120
color_rect_expand_FACTOR : 1.5
mean_color_diff_THRESHOLD_BLUE : 20.0
mean_color_diff_THRESHOLD_RED : 10.0
THRES_MAX_COLOR_RED : 60
THRES_MAX_COLOR_BLUE : 100
light_bar_max_angle : 30.0

# ArmorDetector 参数
corners_expand_ratio : 1.5 # 装甲板角点坐标扩大比例
corners_narrow_ratio : 0.8
is_ture_yolo_armor_brightness_ratio : 1.0
height_correct_ratio_small : 1.22 # 角点坐标修正比例系数 # 1.02 # 0.98 # 1.24 # 1.02
width_correct_ratio_small : 1.12 # 1.12
height_correct_ratio_large : 1.26 # 1.04
width_correct_ratio_large : 1.06
max_angle_diff : 22.5        # 最大角度差 # 22.5 # 30
max_height_diff_ratio : 0.65  # 最大高度差比例 # 0.65 # 1.2
max_length_direction_mismatch_ratio : 1.5 # 最大长度方向错位比例 # 2.0
min_light_distance : 5.0     # 最小灯条距离 
max_light_distance : 50.0    # 最大灯条距离
min_armor_confidence : 0.3   # 最小置信度阈值 # 0.3
#camera_matrix: # 相机内参矩阵
#  - [810.40948926, 0.00000000e+00, 611.41991188]
#  - [0.00000000e+00, 813.22312056, 385.16020552]
#  - [0.00000000e+00, 0.00000000e+00, 1.00000000e+00]
#dist_coeffs: [-0.08153923,  0.49331671,  0.0017929,  -0.00437156, -1.28439103] # 畸变系数
camera_matrix: # 相机内参矩阵
  - [1.31280460e+03, 0.00000000e+00, 6.38736364e+02]
  - [0.00000000e+00, 1.31309593e+03, 5.34133502e+02]
  - [0.00000000e+00, 0.00000000e+00, 1.00000000e+00]
dist_coeffs: [-0.05392145, -0.02516686, -0.00222499, -0.00149047,  0.43693918] # 畸变系数
max_expected_small_distance_mismatch_ratio : 0.35
max_expected_large_distance_mismatch_ratio : 0.7

# ArmorClassifier 参数
MAX_ROI_SAVE_COUNT : 20000  # 最大保存数量
classify_classes : 8
IS_ARMOR_THRESHOLD : 0.5
IS_LARGE_THRESHOLD : 0.5
CLASSIFY_THRESHOLD : 0.5
INPUT_HEIGHT : 48
INPUT_WIDTH : 64
MAX_TRACKING_AGE_MS : 100  # 最大跟踪时间100ms // DEBUG // 100 // 300
MIN_TRACKING_COUNT : 2     # 最小连续跟踪次数           // 2
IS_NEAR_MAX_DIST_RATIO : 1.5     # 50.0
armor_tracker_fit_step : 5
armor_tracker_predict_step : 5

