# ArmorDetect_Node 参数
model_path : "/home/rm1/rm2026/transistor_rm2026_algorithm_visual_ws/src/auto_aim/models/model_rm2026.pt"
enemy_color : "BLUE"
RESET_DISTANCE_THRESHOLD : 400.0 # 单位：mm
MAX_LOST_TIME : 0.5              # 单位：秒
camera_ExposureTime : 1000.0  # 5000.0
camera_Gain : 23.0            # 16.0
bullet_velocity_ : 15.0
current_pitch_ : 0.0
current_yaw_ : 0.0
delta_x_ : 0.0 #    0.0f     48.72f
delta_y_ : 42.8 #   78.31f   -29.14f
delta_z_ : 142.5 #  181.30f  114.34f

pc_ip : "192.168.10.25"
cam_ip : "192.168.10.10"

# Params.h 参数设置
min_light_height : 8 # 8
light_slope_offset : 30
light_min_area : 10
max_light_wh_ratio : 100.0 # 10.0
min_light_wh_ratio : 0.1 # 0.1
light_max_tilt_angle : 60.0
min_light_delta_x : 28
min_light_dx_ratio : 0.8
max_light_dy_ratio : 1.0
max_light_delta_angle : 30.0
near_face_v : 600
max_lr_rate : 0.7
max_wh_ratio : 6.0
min_wh_ratio : 0.5
small_armor_wh_threshold : 3.6
bin_cls_thres : 166
target_max_angle : 20
goodToTotalRatio : 1.0
matchDistThre : 50
wh_ratio_threshold : 3.2
wh_ratio_max : 4.5
M_YAW_THRES : 31416     # 5 degrees in radians (approx)
K_YAW_THRES : 0.7
MAX_DETECT_CNT : 2
MAX_LOST_CNT : 3

# LightBarDetector 参数
binary_img_THRESHOLD : 128 # 128
color_rect_expand_FACTOR : 1.5
mean_color_diff_THRESHOLD_BLUE : 20.0
mean_color_diff_THRESHOLD_RED : 5.0
THRES_MAX_COLOR_RED : 100
THRES_MAX_COLOR_BLUE : 100

# ArmorDetector 参数
corners_expand_ratio : 1.5 # 装甲板角点坐标扩大比例
max_angle_diff : 30        # 最大角度差 # 22.5
max_height_diff_ratio : 1.2  # 最大高度差比例 # 0.65
min_light_distance : 5.0     # 最小灯条距离 
max_light_distance : 50.0    # 最大灯条距离
min_armor_confidence : 0.3   # 最小置信度阈值
camera_matrix: # 相机内参矩阵
  - [810.40948926, 0.00000000e+00, 611.41991188]
  - [0.00000000e+00, 813.22312056, 385.16020552]
  - [0.00000000e+00, 0.00000000e+00, 1.00000000e+00]
dist_coeffs: [-0.08153923,  0.49331671,  0.0017929,  -0.00437156, -1.28439103] # 畸变系数
max_expected_small_distance_mismatch_ratio : 0.35
max_expected_large_distance_mismatch_ratio : 0.35
